@baseUrl = http://localhost:3000
@urlPath = api/v1



GET {{baseUrl}}/{{urlPath}}/testing
Content-Type: application/json
Accept: application/json
withCredentials: true


###
POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email_address": "benjitestingTwo@yahoo.com",
  "password": "r3fcrfrf",
  "child_name": "jean-claude",
  "device_id": "dw134134341341ded"
}


###
POST {{baseUrl}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email_address": "benjitestingOne@yahoo.com",
  "password": "r3fcrfrf",
  "child_name": "jean-claude"
}




###
POST {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

