// for local testing
// @baseUrl = http://localhost:3000

// for serverless offline testing
@baseUrl = http://localhost:3000/dev
@urlPath = api/v1

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9hZGRyZXNzIjoiYmVuaml0ZXN0aW5nT25lQHlhaG9vLmNvbSIsImNoaWxkX25hbWUiOiJqZWFuLWNsYXVkZSIsInBhc3N3b3JkIjoicjNmY3JmcmYiLCJpYXQiOjE2NzUzNzEzODZ9.vEgh9cbNQBLHjxHKq4Bm6PjvUNhoHC60Gu8HsL1f24E

###
POST {{baseUrl}}/{{urlPath}}/add-apps
Content-Type: application/json
Accept: application/json
Authorization: {{accessToken}}
withCredentials: true

[
{
"installed_app_name": "com.mymobile.web",
"app_status": "inactive",
"device_id": "dw134134341341ded"
},
{
"installed_app_name": "com.teamviewer.android",
"app_status": "active",
"device_id": "dw134134341341ded"
}]

###
GET {{baseUrl}}/{{urlPath}}/get-apps/dw134134341341ded
Content-Type: application/json
Accept: application/json
Authorization: {{accessToken}}
withCredentials: true


###
POST {{baseUrl}}/{{urlPath}}/update-app-status
Content-Type: application/jsonx
Accept: application/json
Authorization: {{accessToken}}
withCredentials: true

{
"installed_app_name": "com.mymobile.web",
"app_status": "inactive",
"device_id": "dw134134341341ded"
}




# {
# "installed_app_name": "com.snapchat.android",
# "app_status": "inddactive",
# "device_id": "dw134134341341ded"
# }





#Here's an array of 10 dummy objects:

# [
# {
# "installed_app_name": "com.facebook.react",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.google.maps",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.whatsapp.web",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.snapchat.android",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.twitter.android",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.instagram.android",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.pinterest.android",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.tiktok.android",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.spotify.music",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# },
# {
# "installed_app_name": "com.github.mobile",
# "app_status": "active",
# "device_id": "dw134134341341ded"
# }
# ]
