// for local testing
@baseUrl = http://localhost:4000

// PRODUCTION ON LAMBDA
// @baseUrl = https://7dw32zvl44.execute-api.eu-west-3.amazonaws.com/dev/

// for serverless offline testing
# @baseUrl = http://localhost:3000/dev
@urlPath = api/v1



GET {{baseUrl}}/{{urlPath}}/testing
Content-Type: application/json
Accept: application/json
withCredentials: true


###
POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email_address": "benjitestingFive@yahoo.com",
  "password": "benjamin",
  "child_name": "jean-claude",
  "device_id": "dw134134341341ded"
}


###
POST {{baseUrl}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email_address": "benjitestingFour@yahoo.com",
  "password": "benjamin",
  "child_name": "jean-claude"
}




###
POST {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

